name: Integration Tests

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'

jobs:
  chrome-versions:
    runs-on: ubuntu-16.04
    strategy:
      matrix:
        imageTag:
          - node12.18.0-chrome83-ff77
          - node12.16.2-chrome81-ff75
          - node12.16.1-chrome80-ff73
    container:
      image: cypress/browsers:${{ matrix.imageTag }}
    steps:
      - uses: actions/checkout@v1
      - uses: cypress-io/github-action@v1
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          working-directory: integration
          record: true
          parallel: true
          group: chrome-linux-${{ matrix.imageTag }}
          browser: chrome

  firefox-versions:
    runs-on: ubuntu-16.04
    strategy:
      matrix:
        imageTag:
          - node12.18.0-chrome83-ff77
          - node12.16.2-chrome81-ff75
          - node12.16.1-chrome80-ff73
    container:
      image: cypress/browsers:${{ matrix.imageTag }}
      options: --user 1001
    steps:
      - uses: actions/checkout@v1
      - uses: cypress-io/github-action@v1
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          working-directory: integration
          record: true
          parallel: true
          group: firefox-linux-${{ matrix.imageTag }}
          browser: firefox

  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1
      - uses: cypress-io/github-action@v1
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          working-directory: integration
          record: true
          parallel: true
          group: edge-windows
          browser: edge
